"""empty message

Revision ID: 21e6a430bab5
Revises: b4f6f78bb129
Create Date: 2024-11-11 23:30:26.850891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21e6a430bab5'
down_revision = 'b4f6f78bb129'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seller', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bank_account', sa.String(length=30), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seller', schema=None) as batch_op:
        batch_op.drop_column('bank_account')

    # ### end Alembic commands ###
