"""empty message

Revision ID: 3647cb8adfca
Revises: fe8dff937891
Create Date: 2024-11-04 06:35:38.012187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3647cb8adfca'
down_revision = 'fe8dff937891'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('address', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comprador_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('address_buyer_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'comprador', ['comprador_id'], ['id'])
        batch_op.drop_column('buyer_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('address', schema=None) as batch_op:
        batch_op.add_column(sa.Column('buyer_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('address_buyer_id_fkey', 'comprador', ['buyer_id'], ['id'])
        batch_op.drop_column('comprador_id')

    # ### end Alembic commands ###
