"""empty message

Revision ID: 626bb9575a95
Revises: f82ddf5a01b6
Create Date: 2024-11-06 23:29:16.514146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '626bb9575a95'
down_revision = 'f82ddf5a01b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('address', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=200),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('address', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)

    # ### end Alembic commands ###
