"""empty message

Revision ID: 6f50d167eb85
Revises: fa7ebbc61dc5
Create Date: 2024-11-12 00:01:30.997292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f50d167eb85'
down_revision = 'fa7ebbc61dc5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seller', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seller', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
