"""empty message

Revision ID: 77de346d286f
Revises: b6c23f365316
Create Date: 2024-10-24 02:17:06.948913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77de346d286f'
down_revision = 'b6c23f365316'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('categoria')
    # ### end Alembic commands ###
