"""empty message

Revision ID: 85bae23f222a
Revises: ef59a64d7275
Create Date: 2024-11-12 04:40:38.538506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85bae23f222a'
down_revision = 'ef59a64d7275'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seller', schema=None) as batch_op:
        batch_op.drop_constraint('seller_email_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seller', schema=None) as batch_op:
        batch_op.create_unique_constraint('seller_email_key', ['email'])

    # ### end Alembic commands ###
