"""empty message

Revision ID: 9e2ced6deb6b
Revises: 9d84ea722aee
Create Date: 2024-10-25 07:02:24.344380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e2ced6deb6b'
down_revision = '9d84ea722aee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('direccion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('direccion', sa.String(length=120), nullable=False),
    sa.Column('ciudad', sa.String(length=120), nullable=False),
    sa.Column('codigo_postal', sa.String(length=80), nullable=False),
    sa.Column('pais', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('direccion')
    # ### end Alembic commands ###
