"""empty message

Revision ID: ca749790d961
Revises: 642cb8ec040f
Create Date: 2024-11-10 00:48:09.142775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca749790d961'
down_revision = '642cb8ec040f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comprador', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_image', sa.String(length=500), nullable=True))
        batch_op.drop_column('image')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comprador', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
        batch_op.drop_column('profile_image')

    # ### end Alembic commands ###
