"""empty message

Revision ID: d8b6d96823ab
Revises: 2ab832b12e7a
Create Date: 2024-10-31 02:44:33.324398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8b6d96823ab'
down_revision = '2ab832b12e7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=120), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('postal_code', sa.String(length=80), nullable=False),
    sa.Column('country', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('direccion')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('direccion',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('direccion', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('ciudad', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('codigo_postal', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('pais', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='direccion_pkey')
    )
    op.drop_table('address')
    # ### end Alembic commands ###
