"""empty message

Revision ID: f837893ea8cd
Revises: d8b6d96823ab
Create Date: 2024-10-31 18:47:22.945420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f837893ea8cd'
down_revision = 'd8b6d96823ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seller', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('lat', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('lon', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seller', schema=None) as batch_op:
        batch_op.drop_column('lon')
        batch_op.drop_column('lat')
        batch_op.drop_column('address')

    # ### end Alembic commands ###
