"""empty message

Revision ID: fa7ebbc61dc5
Revises: 21e6a430bab5
Create Date: 2024-11-11 23:40:33.651349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa7ebbc61dc5'
down_revision = '21e6a430bab5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seller', schema=None) as batch_op:
        batch_op.alter_column('bank_account',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=120),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seller', schema=None) as batch_op:
        batch_op.alter_column('bank_account',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=30),
               existing_nullable=True)

    # ### end Alembic commands ###
