"""empty message

Revision ID: fe8dff937891
Revises: 023b9602b082
Create Date: 2024-11-03 23:47:30.678564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe8dff937891'
down_revision = '023b9602b082'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('address', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lat', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('lon', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('buyer_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('seller_id', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint(None, ['seller_id'])
        batch_op.create_foreign_key(None, 'comprador', ['buyer_id'], ['id'])
        batch_op.create_foreign_key(None, 'seller', ['seller_id'], ['id'])
        batch_op.drop_column('city')
        batch_op.drop_column('country')
        batch_op.drop_column('postal_code')

    with op.batch_alter_table('seller', schema=None) as batch_op:
        batch_op.drop_column('address')
        batch_op.drop_column('lat')
        batch_op.drop_column('lon')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seller', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lon', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('lat', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('address', sa.VARCHAR(length=100), autoincrement=False, nullable=True))

    with op.batch_alter_table('address', schema=None) as batch_op:
        batch_op.add_column(sa.Column('postal_code', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('country', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('city', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('seller_id')
        batch_op.drop_column('buyer_id')
        batch_op.drop_column('lon')
        batch_op.drop_column('lat')

    # ### end Alembic commands ###
